---
title: what got me into coding
author: Zac Garland
date: "`r Sys.Date()`"
slug: what-got-me-into-coding
categories:
  - R
  - tidyverse
  - tidyquant
tags:
  - R
  - Rstudio
  - Tidyverse
  - tidyquant
description: "cluster risk, tidyverse, and tidyquant"
featured: code_2.jpg
featuredalt: ''
featuredpath: post
linktitle: ''
type: post
exclude_jquery: true
---

```{r, include=F}
knitr::opts_chunk$set(
  warning = F,
  message = F,
  out.width="100%",
  fig.align='center'
  
)
```


<style>
<!-- table>thead { -->
<!--     background-color: #000; -->

<!-- } -->

table{
color: black;
}

<!-- table.dataTable.stripe tbody tr.odd, table.dataTable.display tbody tr.odd { -->
<!--     background-color: #000000; -->
<!-- } -->

<!-- table.dataTable tbody tr { -->
<!--     background-color: #202020; -->
<!-- } -->
</style>



# R packages

```{r}
library(knitr)
library(DT)
library(plotly)
library(widgetframe)
library(tidyverse)
library(tidyquant)

```

# Fetch Stock Index

```{r}

stock_index <- tq_index("DOW")

stock_index %>% 
  select(symbol,sector,company,weight) %>% 
  mutate(weight = round(weight*100,2)) %>% 
  datatable(options = list(dom = 'tp'),rownames=F)


```

# calculate returns

```{r}

stock_p <- stock_index %>% 
  pull(symbol) %>% 
  tq_get(from = as_date("2000-01-01"))

stock_p <- stock_p %>% 
  select(symbol,date,volume,adjusted) %>% 
  group_by(symbol) %>% 
  mutate(ret = adjusted/lag(adjusted)-1) %>% 
  filter(!is.na(ret)) %>% 
  mutate(cumulative_ret = with_order(date,cumprod,1+ret)-1) %>% 
  ungroup() 


top_five <- stock_index %>% 
  slice(1:5) %>% 
  left_join(stock_p) %>% 
  select(symbol,date,volume,adjusted,ret,cumulative_ret)




top_five %>% 
  slice(1:100) %>% 
  mutate_at(vars(adjusted:cumulative_ret),funs(round(.,2))) %>% 
  datatable(options = list(dom = 't',scrollY = '400px',paging=F),
            rownames=F)

```

# plot

```{r}
top_five %>% 
  plot_ly(x = ~date,
          y = ~cumulative_ret,
          color = ~symbol,
          mode = "lines") %>% 
  layout(plot_bgcolor = "#000000",
         paper_bgcolor = "#000000",
         font = list(color="#ffffff")) %>% 
  config(displayModeBar = F)

```



```{r}

p_dat <- stock_p %>% 
  left_join(stock_index) %>% 
  select(symbol,company,sector,date,weight,adjusted,ret,cumulative_ret) %>% 
  mutate(year = year(date)) %>% 
  group_by(symbol,sector,year) %>% 
  mutate(cumulative_ret = with_order(date,cumprod,1+ret)-1, 
         avg_sd = sd(ret,na.rm=T)*sqrt(252)) %>% 
  filter(date == max(date,na.rm=T)) %>% 
  ungroup()

colors <- c('#4AC6B7', '#1972A4', '#965F8A', '#FF7070', '#C61951')

ax <- list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE
)


p_dat %>% 
  plot_ly(x = ~avg_sd, y = ~cumulative_ret, color = ~sector, size = ~cumulative_ret/avg_sd, colors = colors, frame = ~year,
        type = 'scatter', mode = 'markers', sizes = c(5,50),
        marker = list(symbol = 'circle', sizemode = 'diameter',
                      line = list(width = 2, color = '#FFFFFF')),
        text = ~paste('ticker:', symbol, '<br>sector:', sector, '<br>return:', scales::percent(cumulative_ret),
                      '<br>annualized sd:', scales::percent(avg_sd))) %>% 
    layout(xaxis = list(tickformat = "%", title = "annualized sd"),
           yaxis = list(tickformat = "%", title = "cumulative return"),
           plot_bgcolor = "#000000",
         paper_bgcolor = "#000000",
         font = list(color="#ffffff"),
      showlegend = F) %>% 
  animation_opts(1000) %>% 
  animation_button(visible = F) %>% 
  config(displayModeBar = F)


```

