---
title: Equity Research in R
author: Zac Garland
date: "`r Sys.Date()`"
slug: equity-research-in-r
categories:
  - R
  - equity-research
tags:
  - R
  - Rstudio
  - Tidyverse
  - equityresearchr
description: ''
featured: cluster_cor.png
featuredalt: ''
featuredpath: post
linktitle: ''
type: post
---




<center><h2><a href="https://vimeo.com/360549999">R Equity Research</a> by <a href="https://vimeo.com/user102974957">Zac Garland</a></h2></center>
<div style="position:relative;padding-top:56.25%;">
<iframe src="https://player.vimeo.com/video/360549999?quality=1080p&autoplay=1&rel=0" frameborder="0" allow="autoplay; fullscreen" allowfullscreen
style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
</div>


```{r}
plotly_center <- function(plot){

  shiny::div(plot,align = "center")

}

```


```{r, warning=FALSE,message=FALSE}
library(tidyverse)
library(tidyquant)
library(plotly)


tq_get("AAPL") %>% 
  plot_ly(x = ~date,
          y = ~adjusted,
          mode = "lines") %>% 
  plotly_center()

```